config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'
  resources :lists, only: %i[show new index create destroy] do
    resources :bookmarks, only: %i[new index create]
    resources :reviews, only: %i[create index new]
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :comment, presence: true
  validates :rating, presence: true
  validates :rating, length: { maximum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # before_action :set_bookmark, only: :destroy
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  # def show
  #   search_query = params[:query]
  #   if search_query.present?

  #     sql_query = <<~SQL
  #       movie.title @@ :query
  #     SQL

  #     @bookmarks = @bookmarks.from(:movie).where(sql_query, query: "%#{params[:query]}%")

  #     if @bookmarks.empty?
  #       flash.now[:alert] = "No bookmark found for '#{search_query}'. Please search again."
  #     end

  #   else
  #     @bookmarks = @list.bookmarks
  #   end
  # end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
    @list = List.new

    search_query = params[:query]
    if search_query.present?

      sql_query = <<~SQL
        name @@ :query
      SQL
      @lists = List.where(sql_query, query: "%#{params[:query]}%")
      if @lists.empty?
        flash.now[:alert] = "No lists found for '#{search_query}'. Please search again."
      end
    else
      @lists = List.all
    end
    @lists = @lists.sort_by(&:created_at)
  end

  def show
    @bookmark_new = Bookmark.new
    @bookmarks = @list.bookmarks
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:id])
  end



  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list

    if @review.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieWatchlist</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render "shared/navbar" %>

<div class="container-fluid">
  <div class="row head-row">
      <%= image_tag "cinema.jpg", class: "banner w-100 h-100" %>
      <div class="banner-text text-center py-5 align-center w-50">
        <h1> Amazing Movie Lists</h1>
        <h5>Even create your own!</h5>
        <a class="btn-banner" href="https://troopl.com/20rwillcox" >Reach Out</a>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if @lists.any? %>
      <% @lists.each do |list| %>
          <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
        <%= link_to list_path(list) do %>
            <div class="card index-card m-2 p-2">

              <div class="card-overlay">
                <% if list.photo.key %>
                  <%=  cl_image_tag list.photo.key, class: 'card-img-top' %>
                <% end %>
                <div class="card-title index-card-title w-90 text-center">
                  <h2><strong><%= list.name %></strong></h2>
                </div>
                <div class="text-center">
                  <%= link_to "Remove List", list_path(list), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <em>Sorry, No Lists Yet</em>
    <% end  %>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "shared/navbar-index" %>

<div class="container-fluid">
  <div class="row head-row">
      <%= image_tag "cinema.jpg", class: "banner w-100 h-100" %>
      <div class="banner-text text-center py-5 align-center w-50">
        <h1><%= @list.name %></h1>
        <h5>Bookmarks and list reviews</h5>
        <a class="btn-banner" href="https://troopl.com/20rwillcox" >Reach Out</a>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row d-flex">
    <% @bookmarks.each do |bookmark| %>
      <div class="col col-sm-6 col-md-4 col-lg-4 mt-5">
        <div class="card card-show">     <%# h-100 %>
        <% if !bookmark.movie.poster_url.empty? %>
          <%= image_tag bookmark.movie.poster_url, class: 'card-img-show' %>
        <% end %>
          <div class="card-body card-body-show">
            <h5 class="card-title"> <%= bookmark.movie.title %></h5>
            <p class="card-text card-text-show align-center"> <%= bookmark.movie.overview %></p><br>
            <div class="card-bottom">
              <div><i class="fa-solid fa-star align-bottom mb-1"></i><%= bookmark.movie.rating %></div>
              <p><%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm:"Are you sure?"} %></p>
            </div>
          </div>
          <div class="card-footer card-footer-show text-center">
            <p class="card-text"><strong> My comment: </strong> <br><%= bookmark.comment %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-5">
<h2 class="text-center"> List Reviews </h2>
  <div class="review-cards d-flex justify-content-between">

  <%= render "shared/reviews" %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar-index.html.erb
<nav class="navbar bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <a class="nav-link active mr-3" aria-current="page" href="/"><%= image_tag "popcorn.png" , class: 'logo' %></a>

    <div class="offcanvas-buttons d-flex">
      <%# Bookmark Tab %>
      <div data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <div class="btn-banner mx-2">Bookmark</div>
      </div>
      <div class="offcanvas offcanvasbookmark offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Make a bookmark</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="my-2">
          <%= simple_form_for [@list, @bookmark_new] do |f| %>
            <%= f.association :movie, required: false  %>
            <%= f.input :comment, placeholder: "Great selection.."  %>
            <%= f.submit "New Bookmark", class: "btn-banner" %>
          <% end %>
        </div>
      </div>

      <%# Review Tab %>
      <div data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarReview" aria-controls="offcanvasNavbarReview" aria-label="Toggle navigation">
        <div class="btn-banner mx-2">Review</div>
      </div>
      <div class="offcanvas offcanvasreview offcanvas-end" tabindex="-1" id="offcanvasNavbarReview" aria-labelledby="offcanvasNavbarReviewLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Leave your review</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div>
          <%= simple_form_for [@list, @review] do |f| %>
            <%= f.input :comment, placeholder: "So much fun..", required: false %>
            <%= f.input :rating, as: :select, collection: (1..5), required: false, prompt: "Star Rating" %>
            <%= f.submit "New Rating", class: "btn-banner" %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <a class="nav-link active mr-3" aria-current="page" href="/"><%= image_tag "popcorn.png" , class: 'logo' %></a>

    <%= form_with url: lists_path, method: :get, class: "d-flex align-items-center search" do |form| %>
      <%= form.text_field :query, value: params[:query], class: "form-control me-2", placeholder: "Find a list" %>
      <%= form.submit "Search", class: "btn btn-banner" %>
    <% end %>

    <div data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
      <div class="btn btn-banner">New List</div>
    </div>

    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title align-center mx-auto text-center" id="offcanvasNavbarLabel">Create List</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div>
        <%= simple_form_for @list do |f|%>
        <%= f.input :name, required: false, placeholder: "80's Classics", class: "home-form-input"  %>
        <%= f.input :photo, as: :file, class: "home-form-input" %>
        <div class="d-flex">
          <%= f.submit "Add list", class: "btn btn-banner text-center mx-auto" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_reviews.html.erb
<% @list.reviews.each do |review| %>
  <div class="card-product d-flex justify-content-around">
    <i class="fa-solid fa-user-ninja fa-2xl"></i>

    <div class="card-product-infos text-center">
      <h2 class="mx-auto"> "<em><%= review.comment %></em>"</h2>
      <div class="stars">
        <% num = review.rating.to_i %>
          <% num.times do %>
            <i class="fa-solid fa-star mx-auto" style="color: #f3d512;"></i>
          <% end %>
      </div>
    </div>

  </div>
<% end %>